package com.camgist.snooze

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import com.camgist.snooze.ui.SnoozlooApp
import com.camgist.snooze.ui.theme.SnoozlooTheme
import com.camgist.snooze.util.AlarmIntegrationTest
import com.camgist.snooze.util.AlarmTestUtil
import org.koin.androidx.compose.KoinAndroidContext
import org.koin.core.annotation.KoinExperimentalAPI

// Temporary BuildConfig until the actual one is generated by the build process
object BuildConfig {
    const val DEBUG = true
}

class MainActivity : ComponentActivity() {
    @OptIn(KoinExperimentalAPI::class)
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            KoinAndroidContext {
                SnoozlooTheme {
                    Surface(
                        modifier = Modifier.fillMaxSize(),
                        color = MaterialTheme.colorScheme.background
                    ) {
                        SnoozlooApp(alarmId = intent.getLongExtra("ALARM_ID", -1L))
                    }
                }
            }
        }
        
        // Uncomment this line to run the alarm tests during development
        // runAlarmTests()
    }
    
    /**
     * Run integration tests for alarm functionality
     * This should only be used during development and debugging
     */
    private fun runAlarmTests() {
        if (BuildConfig.DEBUG) {
            // Run standalone alarm calculation tests
            AlarmTestUtil.testAlarmCalculations()
            
            // Run full integration tests
            val integrationTest = AlarmIntegrationTest(this)
            integrationTest.runIntegrationTest()
        }
    }
}